# Generated by Django 3.1 on 2020-08-25 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Input_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=120)),
                ('password', models.CharField(max_length=20)),
                ('user_name', models.CharField(error_messages={'max_length': 'This is too long'}, max_length=2)),
                ('email', models.EmailField(max_length=120)),
                ('language', models.CharField(choices=[('ENG', 'English'), ('DEK', 'German'), ('FRE', 'French')], default='ENG', max_length=3)),
            ],
        ),
    ]
