# Generated by Django 3.1 on 2020-08-25 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('input_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='input_data',
            name='first_name',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
